import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import fonts from '../styles/Fonts.module.css'
import Monitor from '../../public/images/monitor.gif'
import Title from '../components/title'
import Timeline from '../components/timeline'
import ButtonFixed from '../components/buttonfixed'
import CardStyled from '../components/cardstyled'
import icon_css from '../../public/icons/css.svg'
import icon_html from "../../public/icons/html.svg";
import icon_js from "../../public/icons/javascript.svg";
import icon_react from "../../public/icons/react.svg";
import icon_nextjs from "../../public/icons/nextjs.svg";
import icon_tailwind from "../../public/icons/tailwind.svg";
import ImageStyled from '../components/imagestyles'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://brathkennet.github.io/career-portfolio/icons/favicon.ico"
        />
      </Head>

      <header
        className="flex items-center justify-around h-screen bg-no-repeat bg-center bg-cover bg-[url('../../public/images/bg-section1.jpeg')] z-50"
        id="header"
      >
        <div
          className="bg-[black]/25 z-10 backdrop-blur-md border-4 border-[#C00B62] rounded-tr-[52px] rounded-bl-[52px] md:p-16 p-7 m-12"
          data-aos="zoom-in"
        >
          <p
            className={`text-white text-center md:text-5xl text-3xl lg:mb-8 mb-6 ${fonts.font_paytone} ${styles.section_title} `}
          >
            Desarrollo de Aplicaciones Web
          </p>
          <p
            className={`text-white text-center lg:text-2xl text-sm ${fonts.font_paytone} ${styles.section_subtitle}`}
          >
            Portafolio Electrónico
          </p>
        </div>
      </header>

      <section
        className="min-h-screen bg-[#13000E] z-20 pt-28 pb-10 sm:px-28 px-8 max-w-screen"
        id="intro"
      >
        <Title text={"Bienvenida e Introducción"} right={true} />
        <div className="grid c_lg:grid-cols-2 grid-cols-1 xl:px-20 lg:px-5 md:px-0 md:py-12 py-5 place-items-center mt-10">
          <div data-aos="zoom-in-right">
            <Image src={Monitor} height={400} width={400} alt="monitor" />
          </div>
          <div
            className="w-fit h-fit border-x border-white md:mt-0 mt-5 sm:px-10 px-5 sm:py-10 py-5 sm:rounded-[40px] rounded-[20px]"
            data-aos="zoom-in-left"
          >
            <p
              className={`text-white max-w-[400px] text-justify m-auto md:text-[19px] text-base ${fonts.font_bree}
              `}
            >
              ¡Bienvenido al portafolio electrónico de Desarrollo de
              Aplicaciones Web! <br />
              <br /> Mi nombre es Brath, y estoy emocionado de compartir mi
              trabajo y mi trayectoria durante este curso. <br />
              <br />
              En este portafolio encontrarás los temas realizados por cada
              semana. Cada uno de ellos representa un reto para mí y una
              oportunidad para aprender y crecer en mi carrera.
            </p>
          </div>
        </div>
      </section>

      <div className="w-full h-fit bg-[#13000E]">
        <div className="w-[90%] h-[1px] bg-[#C00B62] mx-auto"></div>
      </div>

      <section
        className="h-fit bg-[#13000E] z-20 pt-28 pb-10 sm:px-28 px-8 max-w-screen"
        id="content"
      >
        <Title text={"Contenido"} right={false} />
        <Timeline />
      </section>

      <div className="w-full h-fit bg-[#13000E]">
        <div className="w-[90%] h-[1px] bg-[#C00B62] mx-auto"></div>
      </div>

      <section
        className="h-fit bg-[#13000E] z-20 pt-28 pb-10 sm:px-28 px-8 max-w-screen"
        id="about"
      >
        <Title text={"Sobre Mí"} right={true} />
        <div className="h-fit grid md:grid-cols-2 grid-cols-1 mt-32 mb-10 md:max-w-[85%] max-w-full mx-auto ">
          <ImageStyled />
          <div
            className={`text-white block text-lg text- px-4 m-auto max-w-[500px] text-justify ${fonts.font_bree}`}
            data-aos="fade-up"
          >
            <p className="mb-2">¡Hola! Soy Brath.</p>
            <p className="mb-2">Actualmente estoy estudiando en la UNCP.</p>
            <p>
              No cuento con demasiada experiencia en el Desarrollo de
              Aplicaciones, sin embargo, estoy constantemente buscando
              oportunidades para crecer y aprender en este campo que está en
              constante evolución.
            </p>
          </div>
        </div>
        <div className="max-w-[700px] h-fit py-20 bg-[#13000E] z-10 mx-auto">
          <div className="grid md:grid-cols-6 grid-cols-3 mx-auto relative text-center w-full">
            <CardStyled img={icon_html} delay={"0"} />
            <CardStyled img={icon_css} delay={"100"} />
            <CardStyled img={icon_js} delay={"200"} />
            <CardStyled img={icon_react} delay={"300"} />
            <CardStyled img={icon_nextjs} delay={"400"} />
            <CardStyled img={icon_tailwind} delay={"500"} />
          </div>
        </div>
      </section>
      <ButtonFixed />
    </>
  );
}

